let TECHNIC_UNIT = 8;

let EDGE_MARGIN = 0.2 / TECHNIC_UNIT;
let INTERIOR_RADIUS = 6.4 * 0.5 / TECHNIC_UNIT;
let PIN_HOLE_RADIUS = 5.2 * 0.5 / TECHNIC_UNIT;
let PIN_HOLE_OFFSET = 0.7 / TECHNIC_UNIT;
let AXLE_HOLE_SIZE = 2.02 * 0.5 / TECHNIC_UNIT;
let PIN_RADIUS = 4.63 * 0.5 / TECHNIC_UNIT;
let PIN_LIP_RADIUS = 0.17 / TECHNIC_UNIT;
let AXLE_SIZE_INNER = 1.72 * 0.5 / TECHNIC_UNIT;
let AXLE_SIZE_OUTER = 4.3 * 0.5 / TECHNIC_UNIT;
let AXLE_PIN_ADAPTER_SIZE = 0.8 / TECHNIC_UNIT;
let AXLE_PIN_ADAPTER_RADIUS = 6 * 0.5 / TECHNIC_UNIT;
let INTERIOR_END_MARGIN = 0.2 / TECHNIC_UNIT;

let LIP_SUBDIVISIONS = 6;

let SUBDIVISIONS = 8;