let TECHNIC_UNIT = 8;

let EDGE_MARGIN = 0.19 / TECHNIC_UNIT; // 0.16 -- 0.23
let INTERIOR_RADIUS = 6.2 * 0.5 / TECHNIC_UNIT;
let PIN_HOLE_RADIUS = 5.2 * 0.5 / TECHNIC_UNIT; // 5.0 -- 5.5
let PIN_HOLE_OFFSET = 0.55 / TECHNIC_UNIT; // 0.5 is too small
let AXLE_HOLE_SIZE = 2.1 * 0.5 / TECHNIC_UNIT; // 2.0 -- 2.3
let PIN_RADIUS = 4.8 * 0.5 / TECHNIC_UNIT; // 4.7 -- 5.0
let AXLE_SIZE_INNER = 1.7 * 0.5 / TECHNIC_UNIT; // 1.75 is too large
let AXLE_SIZE_OUTER = 4.2 * 0.5 / TECHNIC_UNIT; // 4.4 is too large
let AXLE_PIN_ADAPTER_SIZE = 0.8 / TECHNIC_UNIT;
let AXLE_PIN_ADAPTER_RADIUS = 6 * 0.5 / TECHNIC_UNIT;
let INTERIOR_END_MARGIN = 0.2 / TECHNIC_UNIT;

let PIN_LIP_RADIUS = 0.4 / TECHNIC_UNIT;
let LIP_SUBDIVISIONS = 6;

let SUBDIVISIONS = 8;